# Generated by Django 5.0.4 on 2026-06-16 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0019_subscriptionplan_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Project', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, null=True, unique=True)),
                ('html_code', models.TextField(blank=True, default='')),
                ('css_code', models.TextField(blank=True, default='')),
                ('js_code', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Developer Project',
                'verbose_name_plural': 'Developer Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DevAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dev_assets/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dojo.devproject')),
            ],
            options={
                'verbose_name': 'Developer Asset',
                'verbose_name_plural': 'Developer Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='devproject',
            index=models.Index(fields=['user', 'is_published'], name='dojo_devpro_user_id_a8c6d5_idx'),
        ),
    ]
