# Generated by Django 5.0.4 on 2026-06-16 22:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('monthly', 'Monthly'), ('half_yearly', '6 Months'), ('yearly', 'Yearly')], max_length=20, unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Duration in days')),
                ('is_active', models.BooleanField(default=True)),
                ('savings_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('savings_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['-duration_days'],
            },
        ),
        migrations.CreateModel(
            name='TutorInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tutor Interest',
                'verbose_name_plural': 'Tutor Interests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor'), ('admin', 'Admin'), ('parent', 'Parent')], db_index=True, default='student', max_length=10)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('spec', models.CharField(blank=True, choices=[('primary', 'Primary (Grades 1–4)'), ('junior', 'Junior (Grades 5–7)'), ('senior', 'Senior (Grades 8–10)'), ('all', 'All Levels')], max_length=20)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('current_belt_idx', models.IntegerField(db_index=True, default=0)),
                ('trial_used', models.BooleanField(default=False)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('curriculum', models.CharField(blank=True, choices=[('cbc', 'Kenya CBC (Competency Based Curriculum)'), ('844', 'Kenya 8-4-4 Curriculum'), ('igcse', 'IGCSE / Cambridge International')], db_index=True, help_text='Educational curriculum (CBC, 8-4-4, IGCSE)', max_length=10, null=True)),
                ('grade', models.CharField(blank=True, help_text='Grade level (e.g., Grade 5, Form 2, Year 10)', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number for parents/guardians', max_length=20, null=True)),
                ('curriculum_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('time_limit', models.PositiveIntegerField(default=0, help_text='Time limit in minutes, 0 for no limit')),
                ('points', models.PositiveIntegerField(default=100)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_received', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=list)),
                ('score', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late')], default='pending', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dojo.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BeltProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt_id', models.CharField(choices=[('white', 'White Belt'), ('yellow', 'Yellow Belt'), ('blue', 'Blue Belt'), ('red', 'Red Belt'), ('black', 'Black Belt'), ('brown', 'Brown Belt'), ('purple', 'Purple Belt'), ('gold', 'Gold Belt'), ('master', 'Master Belt')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('passed', 'Passed')], default='locked', max_length=10)),
                ('passed', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('best_acc', models.FloatField(default=0.0)),
                ('levels_done', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belt_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Belt Progress',
                'verbose_name_plural': 'Belt Progress',
                'ordering': ['user', models.Case(models.When(belt_id='white', then=0), models.When(belt_id='yellow', then=1), models.When(belt_id='blue', then=2), models.When(belt_id='red', then=3), models.When(belt_id='black', then=4), models.When(belt_id='brown', then=5), models.When(belt_id='purple', then=6), models.When(belt_id='gold', then=7), models.When(belt_id='master', then=8), output_field=models.IntegerField())],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_size', models.PositiveIntegerField(default=0)),
                ('attachment_type', models.CharField(blank=True, max_length=50)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Project', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, null=True, unique=True)),
                ('html_code', models.TextField(blank=True, default='')),
                ('css_code', models.TextField(blank=True, default='')),
                ('js_code', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Developer Project',
                'verbose_name_plural': 'Developer Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DevAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dev_assets/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dojo.devproject')),
            ],
            options={
                'verbose_name': 'Developer Asset',
                'verbose_name_plural': 'Developer Assets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FactMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.PositiveSmallIntegerField()),
                ('b', models.PositiveSmallIntegerField()),
                ('seen', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('total_time_ms', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fact Memory',
                'verbose_name_plural': 'Fact Memory',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='dojo.curriculum')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['curriculum', 'level_order'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('past_paper', 'Past Paper'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('notes', 'Revision Notes'), ('exam', 'Exam')], default='quiz', max_length=20)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Expert')], default=1)),
                ('time_limit_minutes', models.IntegerField(default=0, help_text='0 = no limit')),
                ('total_marks', models.IntegerField(default=0)),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='content_pdfs/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True, help_text='OCR extracted text from PDF')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.curriculum')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.grade')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.subject')),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_received', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('belt_earned', 'Belt Earned'), ('inactive', 'Inactive Warning'), ('payment', 'Payment Related'), ('achievement', 'Achievement'), ('weekly_report', 'Weekly Report'), ('assignment', 'Assignment')], default='achievement', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], default='guardian', max_length=50)),
                ('can_pay', models.BooleanField(default=True, help_text='Parent can make payments for this student')),
                ('can_view', models.BooleanField(default=True, help_text="Parent can view student's progress")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_parents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mcq', max_length=20)),
                ('option_a', models.CharField(blank=True, max_length=500)),
                ('option_b', models.CharField(blank=True, max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.TextField()),
                ('marks', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('requires_manual_grading', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Expert')], default=1)),
                ('requires_upload', models.BooleanField(default=False, help_text='Student must upload a working file to answer this question')),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dojo.contentitem')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Streak',
                'verbose_name_plural': 'Streaks',
            },
        ),
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('session_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('activity_date', models.DateField(auto_now_add=True)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('belts_earned', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('score_earned', models.IntegerField(default=0)),
                ('time_taken_ms', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.question')),
            ],
            options={
                'verbose_name': 'Answer Detail',
                'verbose_name_plural': 'Answer Details',
                'ordering': ['question__order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file (PDF, image, Word document, etc.)', upload_to='quiz_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('answer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dojo.studentanswerdetail')),
            ],
            options={
                'verbose_name': 'Student Answer Attachment',
                'verbose_name_plural': 'Student Answer Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('answers', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='dojo.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='studentanswerdetail',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_details', to='dojo.studentquizattempt'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='dojo.subject')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.topic'),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belt_id', models.CharField(choices=[('white', 'White Belt'), ('yellow', 'Yellow Belt'), ('blue', 'Blue Belt'), ('red', 'Red Belt'), ('black', 'Black Belt'), ('brown', 'Brown Belt'), ('purple', 'Purple Belt'), ('gold', 'Gold Belt'), ('master', 'Master Belt')], max_length=10)),
                ('passed', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(default=0.0)),
                ('time_used', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('total_q', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Request',
                'verbose_name_plural': 'Tutor Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(choices=[('first_correct', 'First Correct'), ('white_belt', 'White Belt'), ('yellow_belt', 'Yellow Belt'), ('blue_belt', 'Blue Belt'), ('red_belt', 'Red Belt'), ('black_belt', 'Black Belt'), ('brown_belt', 'Brown Belt'), ('purple_belt', 'Purple Belt'), ('gold_belt', 'Gold Belt'), ('master_belt', 'Master Belt'), ('perfect_belt', 'Perfect Run'), ('speed_run', 'Speed Run'), ('streak_7', 'Week Warrior'), ('century', 'Century')], max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='inactive', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('paystack_subscription_code', models.CharField(blank=True, max_length=100)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100)),
                ('paystack_authorization_code', models.CharField(blank=True, max_length=100)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('initial', 'Initial Payment'), ('renewal', 'Auto Renewal'), ('manual_renewal', 'Manual Renewal'), ('upgrade', 'Plan Upgrade')], default='initial', max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('access_code', models.CharField(blank=True, max_length=100)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('duration_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paystack_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='dojo.usersubscription')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_type', models.CharField(choices=[('multiplication', 'Multiplication Game (Blue Belt+)'), ('curriculum', 'Curriculum Content (CBC/IGCSE/8-4-4)')], max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Trial',
                'verbose_name_plural': 'User Trials',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='dojo_user_email_3f232f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='dojo_user_role_e937aa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['curriculum', 'grade'], name='dojo_user_curricu_cfd635_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['tutor', 'status'], name='dojo_assign_tutor_i_65d156_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['student', 'status'], name='dojo_assign_student_613df3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='beltprogress',
            unique_together={('user', 'belt_id')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'recipient', 'is_read'], name='dojo_chatme_sender__76eb43_idx'),
        ),
        migrations.AddIndex(
            model_name='devproject',
            index=models.Index(fields=['user', 'is_published'], name='dojo_devpro_user_id_a8c6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='factmemory',
            index=models.Index(fields=['user', 'a', 'b'], name='dojo_factme_user_id_721fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='factmemory',
            index=models.Index(fields=['user', 'seen'], name='dojo_factme_user_id_951b4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='factmemory',
            unique_together={('user', 'a', 'b')},
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentlink',
            unique_together={('parent', 'student')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['content_item', 'order'], name='dojo_questi_content_0de3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentactivitylog',
            index=models.Index(fields=['student', 'activity_date'], name='dojo_studen_student_7fbe55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentquizattempt',
            unique_together={('user', 'content_item')},
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['curriculum', 'grade', 'subject'], name='dojo_conten_curricu_81c775_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'content_type'], name='dojo_conten_status_4b2391_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'created_at'], name='dojo_traini_user_id_67ad37_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['belt_id', 'created_at'], name='dojo_traini_belt_id_860ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorrequest',
            index=models.Index(fields=['student', 'status'], name='dojo_tutorr_student_6c6436_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorrequest',
            index=models.Index(fields=['tutor', 'status'], name='dojo_tutorr_tutor_i_733145_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'badge_id'], name='dojo_userba_user_id_63ca2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge_id')},
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='dojo_usersu_user_id_8b205e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['end_date', 'status'], name='dojo_usersu_end_dat_2dea21_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='dojo_paymen_user_id_a118b2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='dojo_paymen_referen_dbed5f_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrial',
            index=models.Index(fields=['user', 'trial_type', 'used'], name='dojo_usertr_user_id_13c3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usertrial',
            index=models.Index(fields=['end_date'], name='dojo_usertr_end_dat_b0c0bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usertrial',
            unique_together={('user', 'trial_type')},
        ),
    ]
