# Generated by Django 5.0.4 on 2026-06-20 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='developer_access_suspended',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, student cannot access Developer Hub'),
        ),
        migrations.AddField(
            model_name='user',
            name='developer_restored_at',
            field=models.DateTimeField(blank=True, help_text='When the developer access was restored', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='developer_restored_by',
            field=models.ForeignKey(blank=True, help_text='Admin who restored the developer access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_restorations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='developer_suspended_at',
            field=models.DateTimeField(blank=True, help_text='When the developer access was suspended', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='developer_suspended_by',
            field=models.ForeignKey(blank=True, help_text='Admin who suspended the developer access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_suspensions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='developer_suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspending developer access'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['developer_access_suspended'], name='dojo_user_develop_d3617f_idx'),
        ),
    ]
