# Generated by Django 4.2.7 on 2026-09-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_user_developer_access_suspended_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='e.g. index.html, styles/main.css', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('is_entry', models.BooleanField(default=False, help_text='If True, this file is rendered in the live preview iframe.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dojo.devproject')),
            ],
            options={
                'verbose_name': 'Developer File',
                'verbose_name_plural': 'Developer Files',
                'ordering': ['path'],
                'indexes': [models.Index(fields=['project', 'path'], name='dojo_devfil_project_8f7bed_idx')],
                'unique_together': {('project', 'path')},
            },
        ),
    ]
