# Generated by Django 4.2.7 on 2026-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_devfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='devasset',
            name='folder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
